### ISSUE TITLE
Phase: asciidoctor-theme

### ISSUE THREAD

**Issue by rrialq** [mydoctor-maven-plugin/mydoctor-maven-plugin#66]
In this phase we'll make tasks related to download to local repository a theme and unzip it to a location.
The `theme` goal in `asciidoctor-lifecycle-maven-plugin` is mapped to this phase.

Although this is not in @abelsromero proposal, it was in my original view of the lifecycle, and the plugin already implements a mojo that manages this functionalities.

I think it is important at this moment a goal that manages artifacts as zip files that works as themes, although in the future the phases `prepare-scm` and `scm` will make this not so relevant as now.

But I am not convinced yet about checkout a theme from a SCM, instead of download an artifact from a repository and/or unzip it to a custom path.

**Comment by abelsromero** [comment]
Would this fall under this step?
Summary: would be possible to have an option to download remote images automatically.
 https://twitter.com/pingtimeout/status/1169592595082821632
