### ISSUE TITLE
Improve travis usage

### ISSUE THREAD

**Issue by khmarbaise** [mydoctor-maven-plugin/mydoctor-maven-plugin#98]
Currently each build will download all the same dependencies which can be prevented by using the cache of travis. Furthermore each time the build does execute two times maven. One in install parat of travis via `mvn install...` as well as `mvn verify`.

**Comment by rrialq** [comment]
Thank you for his improvement.

Sorry that this pull request has been ignored for so long.
My work does not leave me enough free time to continue developing this project, which is progressing very slowly.
